-- Generated by hyprniconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Cleaned and manually reviewed

---@module 'hl'

--###############
--## MONITORS ###
--###############

hl.monitor({
	output = "",
	mode = "preferred",
	position = "0x0",
	scale = "auto",
})

hl.monitor({
	output = "eDP-1",
	mode = "preferred",
	position = "0x0",
	scale = 1,
})

hl.monitor({
	output = "HDMI-A-1",
	mode = "1920x1080@144hz",
	position = "1920x0",
	scale = 1,
})

--##################
--## MY PROGRAMS ###
--##################

local terminal = "kitty"
local fileManager = "nautilus"
local menu = "rofi -show drun -show-icons"

--############################
--## ENVIRONMENT VARIABLES ###
--############################

hl.env("QT_QPA_PLATFORMTHEME", "qt6ct")

--####################
--## LOOK AND FEEL ###
--####################

hl.config({
	general = {
		gaps_in = 2,
		gaps_out = 8,
		border_size = 1,
		resize_on_border = true,
		allow_tearing = false,
		layout = "dwindle",
		col = {
			-- active_border = {
			-- 	colors = { "rgba(33ccffee)", "rgba(00ff99ee)" },
			-- 	angle = 45,
			-- },
			active_border = "rgba(9598b7cc)",
			inactive_border = "rgba(595959aa)",
		},
	},
})

hl.config({
	decoration = {
		rounding = 4,
		rounding_power = 4,
		active_opacity = 1.0,
		inactive_opacity = 1.0,
		shadow = {
			enabled = false,
			range = 4,
			render_power = 3,
			color = "rgba(1a1a1aee)",
		},
		blur = {
			enabled = false,
			size = 3,
			passes = 1,
			new_optimizations = true,
			xray = true,
			ignore_opacity = true,
			vibrancy = 0.0,
		},
	},
})

hl.curve("easy", { type = "spring", mass = 1, stiffness = 500, dampening = 41 })

-- FULLSCREEN
hl.bind("SUPER" .. " + " .. "F", hl.dsp.window.fullscreen())

hl.config({
	dwindle = {
		preserve_split = true,
	},
})

hl.config({
	master = {
		new_status = "master",
	},
})

hl.config({
	misc = {
		force_default_wallpaper = 1,
		disable_hyprland_logo = false,
	},
})

--############
--## INPUT ###
--############

hl.config({
	input = {
		kb_layout = "us",
		follow_mouse = 1,
		accel_profile = "'flat'",
		force_no_accel = false,
		sensitivity = 0,
		touchpad = {
			natural_scroll = true,
			disable_while_typing = true,
			tap_to_click = true,
		},
	},
})

hl.device({
	name = "syna7db5:01-06cb:cd41-touchpad",
	sensitivity = 1.0,
})

hl.device({
	name = "epic-mouse-v1",
	sensitivity = 0,
})

hl.config({
	cursor = {
		no_hardware_cursors = true,
	},
})

--##################
--## KEYBINDINGS ###
--##################

local mainMod = "SUPER"
local lessMod = "ALT"

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "B", hl.dsp.exec_cmd("killall waybar || waybar"))
hl.bind("PRINT", hl.dsp.exec_cmd("hyprshot -m window"))
hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "S", hl.dsp.exec_cmd("hyprshot -m region"))
hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "L", hl.dsp.exec_cmd("hyprlock"))
hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "W", hl.dsp.exec_cmd("~/.config/hypr/rofi-wallpaper.sh"))

hl.bind(mainMod .. " + " .. "return", hl.dsp.exec_cmd("kitty"))
hl.bind(lessMod .. " + " .. "return", hl.dsp.exec_cmd("kitty"))
hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "X", hl.dsp.window.close())
hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "Q", hl.dsp.window.close())
hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "M", hl.dsp.exit())
hl.bind(mainMod .. " + " .. "E", hl.dsp.exec_cmd("nautilus"))
hl.bind(mainMod .. " + " .. "V", hl.dsp.window.float())
hl.bind(lessMod .. " + " .. "d", hl.dsp.exec_cmd("rofi -show drun -show-icons"))
hl.bind(mainMod .. " + " .. "P", hl.dsp.window.pseudo())

-- Move focus with alt + arrow keys
hl.bind(lessMod .. " + " .. "left", hl.dsp.focus({ direction = "left" }))
hl.bind(lessMod .. " + " .. "down", hl.dsp.focus({ direction = "down" }))
hl.bind(lessMod .. " + " .. "right", hl.dsp.focus({ direction = "right" }))
hl.bind(lessMod .. " + " .. "up", hl.dsp.focus({ direction = "up" }))

-- Move focus with mainMod + vim keys
hl.bind(mainMod .. " + " .. "h", hl.dsp.focus({ direction = "left" }))
hl.bind(mainMod .. " + " .. "j", hl.dsp.focus({ direction = "down" }))
hl.bind(mainMod .. " + " .. "l", hl.dsp.focus({ direction = "right" }))
hl.bind(mainMod .. " + " .. "k", hl.dsp.focus({ direction = "up" }))

-- Switch workspaces with alt + [0-9]
hl.bind(lessMod .. " + " .. 1, hl.dsp.focus({ workspace = 1 }))
hl.bind(lessMod .. " + " .. 2, hl.dsp.focus({ workspace = 2 }))
hl.bind(lessMod .. " + " .. 3, hl.dsp.focus({ workspace = 3 }))
hl.bind(lessMod .. " + " .. 4, hl.dsp.focus({ workspace = 4 }))
hl.bind(lessMod .. " + " .. 5, hl.dsp.focus({ workspace = 5 }))
hl.bind(lessMod .. " + " .. 6, hl.dsp.focus({ workspace = 6 }))
hl.bind(lessMod .. " + " .. 7, hl.dsp.focus({ workspace = 7 }))
hl.bind(lessMod .. " + " .. 8, hl.dsp.focus({ workspace = 8 }))
hl.bind(lessMod .. " + " .. 9, hl.dsp.focus({ workspace = 9 }))
hl.bind(lessMod .. " + " .. 0, hl.dsp.focus({ workspace = 10 }))

-- Switch workspaces with mainMod + [0-9]
hl.bind(mainMod .. " + " .. 1, hl.dsp.focus({ workspace = 1 }))
hl.bind(mainMod .. " + " .. 2, hl.dsp.focus({ workspace = 2 }))
hl.bind(mainMod .. " + " .. 3, hl.dsp.focus({ workspace = 3 }))
hl.bind(mainMod .. " + " .. 4, hl.dsp.focus({ workspace = 4 }))
hl.bind(mainMod .. " + " .. 5, hl.dsp.focus({ workspace = 5 }))
hl.bind(mainMod .. " + " .. 6, hl.dsp.focus({ workspace = 6 }))
hl.bind(mainMod .. " + " .. 7, hl.dsp.focus({ workspace = 7 }))
hl.bind(mainMod .. " + " .. 8, hl.dsp.focus({ workspace = 8 }))
hl.bind(mainMod .. " + " .. 9, hl.dsp.focus({ workspace = 9 }))
hl.bind(mainMod .. " + " .. 0, hl.dsp.focus({ workspace = 10 }))

-- Move active window to a workspace with mainMod + SHIFT + [0-9]
hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 1, hl.dsp.window.move({ workspace = 1 }))
hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 2, hl.dsp.window.move({ workspace = 2 }))
hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 3, hl.dsp.window.move({ workspace = 3 }))
hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 4, hl.dsp.window.move({ workspace = 4 }))
hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 5, hl.dsp.window.move({ workspace = 5 }))
hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 6, hl.dsp.window.move({ workspace = 6 }))
hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 7, hl.dsp.window.move({ workspace = 7 }))
hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 8, hl.dsp.window.move({ workspace = 8 }))
hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 9, hl.dsp.window.move({ workspace = 9 }))
hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 0, hl.dsp.window.move({ workspace = 10 }))

-- Monitor to Workspace Bindings
for ws = 1, 8 do
	hl.workspace_rule({ workspace = ws, monitor = "HDMI-A-1" })
end
hl.workspace_rule({ workspace = 9, monitor = "eDP-1" })
hl.workspace_rule({ workspace = 10, monitor = "eDP-1" })

hl.bind(mainMod .. " + " .. "S", hl.dsp.workspace.toggle_special("magic"))
hl.bind(mainMod .. " + " .. "G", hl.dsp.group.toggle())
hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "R", hl.dsp.exec_cmd("hyprctl reload"))
hl.bind(mainMod .. " + " .. "TAB", hl.dsp.group.next())
hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "TAB", hl.dsp.group.next({ forward = false }))

hl.config({
	group = {
		groupbar = {
			enabled = true,
			height = 0,
			render_titles = true,
			col = {
				active = "rgba(4ade8033)",
				inactive = "rgba(2a2a2a99)",
			},
			text_color = "rgb(4ade80)",
			rounding = 0,
			gradients = false,
		},
	},
})

hl.bind(mainMod .. " + " .. "mouse_down", hl.dsp.focus({ workspace = "e-1" }))
hl.bind(mainMod .. " + " .. "mouse_up", hl.dsp.focus({ workspace = "e+1" }))
hl.bind(mainMod .. " + " .. "comma", hl.dsp.focus({ workspace = "e-1" }))
hl.bind(mainMod .. " + " .. "period", hl.dsp.focus({ workspace = "e+1" }))
hl.bind(lessMod .. " + " .. "Tab", hl.dsp.focus({ workspace = "previous" }))

hl.bind(mainMod .. " + " .. "mouse:272", hl.dsp.window.drag(), { mouse = true })
hl.bind(mainMod .. " + " .. "mouse:273", hl.dsp.window.resize(), { mouse = true })

-- Fastedit Submap (Fixed with native resizing rules)
-- hl.define_submap("fastedit", function()
-- 	hl.bind("CTRL + right", function()
-- 		hl.dispatch(hl.dsp.window.resize({ x = 10, y = 0, relative = true }))
-- 	end)
-- 	hl.bind("CTRL + left", function()
-- 		hl.dispatch(hl.dsp.window.resize({ x = -10, y = 0, relative = true }))
-- 	end)
-- 	hl.bind("CTRL + up", function()
-- 		hl.dispatch(hl.dsp.window.resize({ x = 0, y = -10, relative = true }))
-- 	end)
-- 	hl.bind("CTRL + down", function()
-- 		hl.dispatch(hl.dsp.window.resize({ x = 0, y = 10, relative = true }))
-- 	end)
-- 	hl.bind("SHIFT" .. " + " .. "left", { direction = "l" })
-- 	hl.bind("SHIFT" .. " + " .. "right", { direction = "r" })
-- 	hl.bind("SHIFT" .. " + " .. "up", { direction = "u" })
-- 	hl.bind("SHIFT" .. " + " .. "down", { direction = "d" })
-- 	hl.bind("escape", hl.dsp.submap("reset"))
-- end)

hl.bind(mainMod .. " + " .. "A", hl.dsp.submap("fastedit"))

-- Nvidia Environment Variables
hl.env("LIBVA_DRIVER_NAME", "nvidia")
hl.env("__GLX_VENDOR_LIBRARY_NAME", "nvidia")
hl.env("WLR_DRM_DEVICES", "/dev/dri/card1")
hl.env("WLR_NO_HARDWARE_CURSORS", 1)
hl.env("GBM_BACKEND", "nvidia-drm")
hl.env("AQ_DRM_DEVICES", "/dev/dri/card0:/dev/dri/card1")
hl.env("QT_QPA_PLATFORM", "wayland")
hl.env("SDL_VIDEODRIVER", "wayland")

-- Multimedia Keys
hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+"), { locked = true })
hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"), { locked = true })
hl.bind("XF86AudioMute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"), { locked = true })
hl.bind("XF86AudioMicMute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle"), { locked = true })
hl.bind("XF86MonBrightnessUp", hl.dsp.exec_cmd("brightnessctl s 10%+"), { locked = true })
hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("brightnessctl s 10%-"), { locked = true })
hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "left", hl.dsp.exec_cmd("ddcutil setvcp 10- 10"))
hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "right", hl.dsp.exec_cmd("ddcutil setvcp 10+ 10"))

hl.bind("XF86AudioNext", hl.dsp.exec_cmd("playerctl next"), { locked = true })
hl.bind("XF86AudioPause", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPlay", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPrev", hl.dsp.exec_cmd("playerctl previous"), { locked = true })

hl.config({
	xwayland = {
		force_zero_scaling = true,
	},
})

-- Autostart
hl.on("hyprland.start", function()
	hl.exec_cmd("kitty")
	hl.exec_cmd("nm-applet &")
	hl.exec_cmd("waybar & swaync & hyprpaper & hypridle & hyprpanel & hyprsunset")
end)

-- Exec (run every reload)
hl.on("config.reloaded", function()
	hl.exec_cmd('gsettings set org.gnome.desktop.interface color-scheme "prefer-dark"')
end)
