-- Generated by nwg-displays on 2026-06-30 at 12:57:00. Do not edit manually.

hl.monitor({
    output = "desc:GIGA-BYTE TECHNOLOGY CO. LTD. G24F 2 24080B001379",
    mode = "1920x1080@144.0",
    position = "1920x0",
    scale = 1.0
})
hl.monitor({
    output = "desc:AU Optronics 0x21ED",
    disabled = true
})
