return {
	"nvim-treesitter/nvim-treesitter",
	build = ":TSUpdate",
	lazy = false,
	main = "nvim-treesitter.config",
	opts = {
		ensure_installed = {
			"lua",
			"python",
			"javascript",
			"typescript",
			"vimdoc",
			"vim",
			"regex",
			"sql",
			"dockerfile",
			"json",
			"java",
			"gitignore",
			"graphql",
			"yaml",
			"markdown",
			"bash",
			"tsx",
			"css",
			"html",
		},
		auto_install = true,
		highlight = { enable = true },
		indent = { enable = true },
	},
}